### ISSUE TITLE
Добавить лицензию на код сайта

### ISSUE THREAD

**Issue by ForNeVeR** [fsharplang-ru/fsharplang-ru.github.io#6]
Сейчас у нас лицензия нигде не написана, и надо **как можно скорее** с этим определиться и заручиться согласием всех контрибьюторов.

Я предлагаю для кода сайта использовать MIT.

@Neftedollar, @Worldbeater, @FoggyFinder, прошу написать в комментариях, согласны ли вы на смену лицензии на MIT.

**Comment by FoggyFinder** [comment]
Конечно :)

**Comment by Neftedollar** [comment]
Да, звучит разумно. Некоторые переводные статьи содержат другие лицензии. Возможно не совсем совместимые с MIT. Поэтому все же у каждого перевода должна быть своя лицензия, совместимая с лицензией перевода.

**Comment by worldbeater** [comment]
Согласны :)

**Comment by ForNeVeR** [comment]
@Neftedollar, поскольку переводы у нас публикуются в отдельном репозитории, про их лицензии я в данной задаче не говорил. Лицензии на переводы мы, скорее всего, оставим как в оригиналах было, с пометкой лицензии в каждом материале.

Раз все согласны, то я сегодня добавлю лицензию в репозиторий.
