### ISSUE TITLE
Текст сливается с фоном, варианты решения?

### ISSUE THREAD

**Issue by Neftedollar** [fsharplang-ru/fsharplang-ru.github.io#7]
![image](https://cloud.githubusercontent.com/assets/1009015/25594769/b1eee7c2-2eca-11e7-9aa7-3e8b44612b99.png)
Сейчас текст "F# позволяет разработчикам решать сложные задачи с помощью простого и выразительного кода." сливается с белым фоном на экране монитора ноутбука.
Это не удобно и возможно создает негатив, что в нашем случае не хорошо. 
Возможно стоит доабвить легкий затемненный фон для надписи.
Взмоджно этот фон стоит растянуть во всю длинну. 
Возможно есть другие варианты, было бы хоршо о них узнать.
Очень важно мнение @Worldbeater  по этому вопросу)

**Comment by worldbeater** [comment]
Могу предложить такой вариант: заменить монитор ноутбука скриншотом тёмной темы вижуалстудии + наложить на текущий фон черный слой с прозрачностью 10-15%.

Либо можно попробовать поискать другие мокапы, а то у этого с монитора тени исчезли.

**Comment by ForNeVeR** [comment]
Если внимательно присмотреться, то заметно, что не только с ноутбуком он сливается. Есть ещё проблема в этом районе:
![image](https://cloud.githubusercontent.com/assets/92793/25603336/12ba0582-2f25-11e7-9de5-10cb08140dbe.png)

Я попробовал поиграться с тенью у текста, но это ничего не дало :(

**Comment by worldbeater** [comment]
Запилил новый мокап, обсуждаем-с.

<img src="https://cloud.githubusercontent.com/assets/6759207/25641769/9f837768-2f9e-11e7-8117-c4201ca051ec.png" width="350">

За основу взяты картинки доброго человека с Dribbble: https://dribbble.com/shots/3073093-FREE-3-Macbook-Mockups

UPD:
Закоммитил новый фон. И ещё немного осовременил UI.
